// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0QQSnT5SitfxQU-CGVnYlpPcVBUVm0pw',
    appId: '1:841916085039:web:e54cd6faa64116401da7da',
    messagingSenderId: '841916085039',
    projectId: 'graphql-firebase-flutter',
    authDomain: 'graphql-firebase-flutter.firebaseapp.com',
    storageBucket: 'graphql-firebase-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEjCzlyL_KQQSff6hoXLe6i8Lmi8Z2D-8',
    appId: '1:841916085039:android:f95f2c5d87fd22ff1da7da',
    messagingSenderId: '841916085039',
    projectId: 'graphql-firebase-flutter',
    storageBucket: 'graphql-firebase-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0oktQEFkFxoo-dhhTSgSk7GG-19GqKQ0',
    appId: '1:841916085039:ios:44cb7c7c9884a1321da7da',
    messagingSenderId: '841916085039',
    projectId: 'graphql-firebase-flutter',
    storageBucket: 'graphql-firebase-flutter.appspot.com',
    iosClientId: '841916085039-c1h5e4k5smot5pllouqdveidgvs1adtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseGraphql',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0oktQEFkFxoo-dhhTSgSk7GG-19GqKQ0',
    appId: '1:841916085039:ios:dde04eb40a24ed961da7da',
    messagingSenderId: '841916085039',
    projectId: 'graphql-firebase-flutter',
    storageBucket: 'graphql-firebase-flutter.appspot.com',
    iosClientId: '841916085039-964c0b0qqda6emnpv94q6ki86578guib.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseGraphql.RunnerTests',
  );
}
